### ISSUE TITLE
Release strategy: 0.19 and 1.0

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1797]
cats-1.0 is here.  cats-effect-1.0 is imminent.  fs2-1.0 is expected quickly thereafter.  Dependency releases historically prompt http4s releases  Let's talk.

Goals:
- A stable release on cats/cats-effect/fs2-1.0 stack ASAP.
- Minimize disruptive upgrade cycles.
- Don't release our 1.0 with known warts.
- Maintain no more than two branches (production release and master).

Proposal:
- A conservative 0.19.0 on fs2-1.0.  EOL 0.18.x at this time.
- A glorious 1.0 when it's done, with scalafix from 0.19.

Big ticket items under consideration which may or may not be considered for 0.19:
- [x] HttpApp and HttpRoutes (#1693) 
- [ ] scala.js support (#956)
- [ ] header reform (#1143)
- [ ] websockets as a response type instead of embedded in `Response` 
- [ ] message typeclass (#1572)
- [ ] elimination of backticks
- [x] cancellation support in blaze-server and servlet
- [x] cancellation support in client
- [ ] URI reform (see sttp interpolator for inspiration)
- [ ] server and client creation that returns a `Resource` (relates to #1025)
- [ ] client form (#1772)
- [ ] investigate fastparse as FP-friendly alternative to parboiled2
- [ ] proxy support in blaze-client #1182
- [ ] websocket support in client
- [x] scala-2.13 support (if the dependencies are there)

Breaking changes already in master.:
- [x] Add accumulating version of circe EntityDecoder #1647
- [x] Add ETag support to StaticFile #1652
- [x] Reintroduce the option for fallthrough for authenticated services #1670
- [x] Separate Cookie into RequestCookie and ResponseCookie #1676
- [x] Add Eq[Uri] instance #1688
- [ ] Deprecate Message#withBody in favor of Message#withEntity. The latter returns a Message[F] rather than an F[Message[F]]. #1694
- [x] Myriad new Arbitrary and Cogen instances #1677
- [x] Add non-deprecated LocationResponseGenerator functions #1715
- [x] Relax constraint on Router from Sync to Monad #1723
- [x] Drop scodec-bits dependency #1732
- [x] Add Show[ETag] instance #1749
- [x] Replace fs2.Scheduler with cats.effect.Timer in Retry #1754
- [x] Remove Sync constraint from EntityEncoder[Multipart] #1762
- [x] async-http-client-2.4.2
- [x] blaze-0.14
- [x] scala-xml-1.1.0

For an initial pass, we'll checked the things that belong in 0.19.  Once we have a general consensus on strategy, we'll use the milestone feature and more clearly define 0.19 and 1.0 and fight over the details.

**Comment by rossabaker** [comment]
#1694 is the troubling one: that's the change that's going to be the biggest breakage.  But it's already on master, so it would be tricky to back out without maintaining 0.18 + 0.19 + 1.0 in the short term, and I _really_ don't want to do that.

**Comment by rossabaker** [comment]
A bunch of things are blocked on the weakness of our `Uri` implementation, and the current state is half-baked with some things moved into the `Uri` companion and made a proper `HttpCodec` and others not.  That's a more aggressive change than I want in 0.19, but my biggest embarrassment in 0.18.

**Comment by rossabaker** [comment]
On the subject of avoiding three branches: what happens if we have more things like #1694 before 0.19 is done, but are considered too aggressive for our 0.19 goals?  Is there any way to avoid the three-branch strategy?  Keep in mind that 0.19.0 date is in the hands of the fs2 team, not us.

**Comment by jmcardon** [comment]
I am :+1: the conservative strategy here.

**Comment by rossabaker** [comment]
Okay, to keep things moving:

- master will become 1.0.0-SNAPSHOT
- if it's ready, it goes on master
- when fs2-1.0 release candidates draw near, we'll evaluate whether to build an 0.19 off 0.18 plus carefully limited backports

**Comment by cquiroz** [comment]
:+1:

**Comment by david-mcgillicuddy-ovo** [comment]
Cats-effect 1.0.0 has been released now: https://github.com/typelevel/cats-effect/releases/tag/v1.0.0

**Comment by orium** [comment]
Fs2 1.0 is out :tada: Anyone known when http4s 0.19 will be released?

**Comment by rossabaker** [comment]
We have a milestone, v0.19.0-M4, built on fs2-1.0.0 already.  (There is an identical 0.19.0, but that was an error on my part).  Look for an 0.19.1 on which we'll support binary compatibility within a week or so.

**Comment by orium** [comment]
> There is an identical 0.19.0, but that was an error on my part

@rossabaker maybe you can remove the tag 0.19.0 to avoid confusion.  Shouldn't break `git pull` for anyone since it is just a tag.

**Comment by rossabaker** [comment]
We can't delete it from Maven Central, and I think it's important that people know what source they're running.  I'm inclined to leave it.  But I can't wait to bury it with 0.19.1.

**Comment by orium** [comment]
Ah, if it is published definitely keep the tag :)

**Comment by rossabaker** [comment]
This is super old.
