### ISSUE TITLE
Documentation meta-ticket

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#679]
I have an open ticket at work to improve the docs, and we've had a couple people offer to help.  From Gitter:

> Can somebody who knows the library quite well create tickets for parts that need documentation? I could then try them out and try to document them. I think many people would want to benefit from http4s but it's hard to get started.
- [x] request matching in http4s-dsl
- [x] JSON codecs, including how to make them work with case classes
- [x] basic client operations
- [ ] how to configure a client (IMO, SimpleHttpClient is almost always a bad choice)
- [x] adding headers to a request
- [x] creating and manipulating URIs
- [ ] what's the difference between `Request` and `Task[Request]`?
- [ ] Websockets
- [x] Serve static files
- [ ] Interruptable ServerApp
- [x] how to get cookies from a request
- [ ] how to "reload like Play" (we don't, but sbt-revolver is cool)

If you want to work on one of these, please comment and claim it.

If you want to propose something else, please comment and we'll add it.

**Comment by kevinmeredith** [comment]
Could you please add (or point me to) how to deal with handling a route, e.g. `POST /foobar` that has a payload? 

Perhaps `JSON codecs, including how to make them work with case classes` covers this case.

**Comment by rossabaker** [comment]
@kevinmeredith: Here's an example of [decoding a UrlForm from a POST](https://github.com/http4s/http4s/blob/master/examples/src/main/scala/com/example/http4s/ExampleService.scala#L93-L105).  The key concept is the `EntityDecoder`.  You can [get one for JSON like this](https://github.com/http4s/http4s/blob/master/examples/blaze/src/main/scala/com/example/http4s/blaze/ClientExample.scala#L22-L29), and then you'd be able to `req.decode[Foo]`.  I welcome a debate on whether `fooDecoder` should be optional in that example at #660.

**Comment by rossabaker** [comment]
There is also the [documentation label](https://github.com/http4s/http4s/labels/documentation), which shows a few related issues for us to tackle.

**Comment by rossabaker** [comment]
@reactormonk is improving the JSON and URI situation over on #689.

**Comment by cquiroz** [comment]
I'd like to chime in, perhaps, `adding headers to a request` and #568 

Is there some info on where the documentation is stored and how to compile it with tut?

**Comment by rossabaker** [comment]
Docs live [here](https://github.com/http4s/http4s/tree/master/docs), with a readme on roughly what goes where and how to preview it.

**Comment by reactormonk** [comment]
A few things:

- [ ] Websockets
- [ ] Serve static files
- [ ] Interruptable `ServerApp`

**Comment by rossabaker** [comment]
Added those from the comment above.  By Interruptable ServerApp, you mean the `cancelable in Global` and ^C trick?  That's come up a few times.  Also, `fork := true`.

**Comment by reactormonk** [comment]
Exactly the ^C stuff.

**Comment by toddburnside** [comment]
Here are some of my thoughts wrt documentation from the perspective of someone just starting to use http4s. 

First, it'd be nice to have an overview of the architecture of http4s so the user could see where their code fits into the picture. This could be fairly high level. 

An explanation of Task might be appropriate since it is so integral, and, for me at least, was an important reason for wanting to use http4s. Maybe include some references to other documentation for Task, and explanations of the benefits over Future.

After the descriptions of the pieces (Request, Response, Service, Middleware, etc)., I would really like to see some explanations of how these pieces compose and how you can build up more complex routes and services. Documentation for request pattern matching (already mentioned above) would also be very useful.

**Comment by dbousamra** [comment]
@toddburnside I had a crack the other day coming at it from the angle you described. It's super rough, but I guess it might be useful as inspiration or something: 

https://gist.github.com/dbousamra/f58354b0b3f273649dbf782ddd17b32c

**Comment by rossabaker** [comment]
I'm going to see if I can work some of @dbousamra's ideas into #782 while I'm on an airplane this weekend.  Watch this space.

**Comment by toddburnside** [comment]
@dbousamra Yes, that's the kind of think I was thinking of. I'm glad Ross is running with it. :smile: 

@rossabaker I need to do some proof-reading,  but I'm just about done with some docs on middleware in general, and CORS and GZip in particular. Given the documentation churn at the moment, would it be simpler if I waited until the dust settled before putting in a PR?

**Comment by rossabaker** [comment]
@toddburnside: I'd say topic/hugo is where the fun is happening right now.  I would suggest targeting that.  If that branch turns into a flaming wreckage, I can rescue any markdown you contribute.

**Comment by reactormonk** [comment]
Closed in favour of https://github.com/http4s/http4s/projects/1
